#import "/template.typ": *

= Turning Awareness on Itself

Let's get into the awareness practice if you're not already in phase three, essentially just nice and firm in awareness---as awareness. So that's what happens: the very thing searching for awareness, or searching for enlightenment, is awareness. Okay? That is the cognition. That's just a more coarse, active part of consciousness within consciousness.

So the invitation here is to relax, letting all four foundations of mindfulness settle in their own place. So any emotional energy, we don't need to modify or analyze or apply some kind of antidote. And remember, this is Madhyamaka, the middle way, so if you need to put a band-aid on your cut, that's okay. Oftentimes antidotes can lead to internal grasping and congesting our situations rather than just letting them settle out naturally. We've been calling it "echoing out." Somehow [sangha member's name] got us to start saying "evaporating." Whatever you want to call that, it's fine.

But it's settling in its own place. It's self-liberation, right? It's _rangzhin_ in Tibetan, and we're starting to get used to letting be. No matter if we're in a dramatic situation, a restful situation, etc.---to let our feelings, our thoughts, our body, and the environment just be---and let it come undone by itself. And so I want to get into this for you more advanced yogis. And if you're not feeling me, if you're not hearing me, it's totally fine. Okay? You don't need to try to remember any of this. Don't, you know... you don't need to get agitated, if you're not understanding it, you don't need to look for it even. But no matter what I'm saying here, you'll be able to access to some degree.

But basically, when you turn off the headlights, "consciousness with surface" where we're hooking into stuff, we have thoughts on our mind and so we are captivated. So eventually... "slightly up-aligning here," eventually you get to the point where you're not on a train of thought, you're not stuck in an emotion, and you're able to turn off your headlights of focusing into stuff. And now you're just in a kind of passivity, like taking a bath. #btw[Dawai breathes out, relaxing]. You're just resting in awareness, which is like space---encompassing the body, the emotions, the thoughts, and the environment. Like you're in a snow globe. You know, your mind is sort of everywhere now and so you can successfully let our interaction with the environment be as well. So if some sound is happening or some sights are appearing, we just let that settle in its own place as well.

But here's the part that may be a little bit advanced: so if I'm turning off my headlights, I'm not even looking at you all right now. Awareness is surrounding my body, so to speak. It is my body, including the eyes, the eyeballs, right? And seeing itself, and all the appearances, is now just here. And now I still have a subtle feeling, maybe, of... me sitting here. What's left over when there are no more thoughts, no strong emotional energy, nothing in the body is distracting us? What's left over? There's a subtle---you know, you may even see it somatically in the neck and the shoulders---there's still subtle feelings here. And that's what they used to, I suppose they still call it, "turning awareness in on itself."

Every little detail, every little sensation that you have in your body right now is resting in awareness; it's there. So if I have a thought right now about the moon being bright, that's obviously in my awareness naturally. And I never need to program awareness to say, "Okay, I'm going to think the moon is bright and you be aware while I'm thinking that." We don't have to do that. And so if I have some kind of emotional upheaval right now, or just normal excitation, then I'm allowing that also to oscillate through like a wind through the sky.

And that's what they're using in cognitive science with this high success rate. So that's why it's benefiting so many people in our groups, because it actually works. It's bona fide. Verified. And so we're taking it a little further because we're explicitly recognizing that which holds the panic attack. So in cognitive therapy right now, in the past five years or so they would just say, "Be there with the panic attack." And you would say, "Okay." And you'd be in it. And they even say, "Strap yourself to a chair." It's a feeling like that because you feel like you're rumbling, you're in it. But as awareness practitioners, you won't really feel that. You're not isolated into the panic anymore.

Even if you're a beginner, you're starting to access your mind outside of the body, outside of the elements, outside of the earth and the atmosphere. The great mind that holds you while you're sleeping and waking. The very basis, right? And this is something we need to verify. It's like we're stuck in a dream and somebody's saying, "Hey, this whole thing is mind." And you're just too distracted. You're just too caught up. You don't even listen to the person. Like me, always looking for my dogs in my dreams. Somebody could say, "Hey, it's just a dream. Your dogs are actually, this time they're actually still in the house." And I would just continue looking frantically, wouldn't I? Because I'm so convinced of it.

But let's say somebody really shakes me up and says, "No, this is all mind. This is all your mind, even me." And then you start to see, even though you're in a dream, "Wow, my mind is actually everywhere. It encompasses, right? It's vast and encompassing my experience." This is something you need to verify, you need to test. It's not a belief system. And we hook onto the very nature, which is awareness. So even if it is a dream, there's still this nature of the dream which is cognizance.

So it's like the dreamer who's sitting there chasing his dogs all of a sudden saw, "Wow, me running right now, me chasing, this is all cognition." But you have to start with awareness. You see, you can't really see that it's all consciousness at first. And you can use your logic, your rationale to get there. Space is alive, atoms are alive, particles are alive---whole thing's living. So then all of a sudden you use awareness, you see this awareness that's in even my dogs. Let's say in my dream I catch a dog and I put him on a leash or tell him, "Come on, come." All that is living intelligence---that's cognition. The only difference, I would say, typically with the waking state is that you have other minds that can tap into the dream. Usually, when you go to sleep, are other minds there? But you're pretty compartmentalized, you're psychically isolated.

Unless you're special, you talk to people in your dreams; that's totally awesome. And I believe you. I'm done not believing people, everybody. Whatever you say now, I will believe it from now on. If you tell me you're astral projecting to Pluto and speaking to the archangel Michael with St. Germain, I believe you 100%. I'm done, I'm done challenging people. It's too much work. It's easier to just go along with the delusion. "Oh, St. Germain, really? Oh my God, me too. I was raising my vibration with St. Germain in the sixth dimension in one of my dreams earlier, yeah." Oh god.

So as mind scientists, you know, as equals here, everybody's truth has so much validity yet has none whatsoever, right? So as mind scientists, we can start to at least pull out of our involvement a little bit into this dream and test: what if I pull my hooks out? Let it be---let it settle in its own place. Is my mind really everywhere like that? Ooh, and then the whole thing shifts on you. It's not what you thought it was. And it gets bigger and bigger and more ineffable, right? Everything that's happening is a co-emergence of your mind.

Think about, once you pull out of your distraction and your subscriptions into reification and crystallization of the five wisdoms, the five lights into the elements---once you start to pull out of that, let them settle in their own place and let them de-crystallize. Wow. #btw[Dawai pauses]. So mind is vast, I think that's how we can benefit beings far away or seemingly far away, and continue to be persistent with compassion when beings in our sphere of influence, so to speak, want to engage in non-virtue and destructive behavior.

You know, there's advanced people right now. And there are many compassionate advanced people. But there's advanced people that are just misdirected, misguided, and so we can begin revolutionizing the collective. I think that's what we're doing and why we have so much support as a gathering. When you free your mind, it's so powerful. And we're going together, okay?

We're gonna get straight to the point and that way you don't have to waste any more time and energy. Those who are sincere about the view, about liberating your mind---that's the truest thing we can do right now. If there are terrible things happening in the world, free your mind. If you're suffering, free your mind. If other people are suffering, hen-lightenment is the answer.

Okay last time, just very proud of myself for that one. For those who don't know, Yeshé said, "Why did the chicken cross the road?" and I said, "He wanted to reach Hen-lightenment." Now, I had to bring it up three more times, okay, just to get the smile. We're just smiling, taking it easy, nice and light.

And you know there's many people, the sangha is huge, who are witnessing this liberation, this freedom, this spaciousness. And yeah, you're still kind of going through your stuff here and there and getting caught up in your contemplations and having your desires cycle through. Yes, but you're free; the chains are broken. Many teachers talk about that. Once you have the realization of awareness as the nature of mind, there's really no turning back. Particularly if you're around people who are insistent, that make sure that you have it, then yeah, there is no turning back from that, because you've tasted sugar and it's like, "Wow, you've had this taste." And going back into contraction, going back into what they would call samsara and into conditioned existence, it just feels wrong, right? It feels icky.

So that's all I had to say. The main point there was allowing every last sensation that you have here to liberate out. They're really like contractions. And we can allow them to liberate out, so that would include the conditioned self. That's what I'm sort of pointing to, okay? The conditioned self liberating out. The main contraction, that initial factor in all stress and suffering---it's the very start of everything is that little divide that we create. We have our whole mind here and then we created a divide in there. So now there's one part of our mind navigating around in another part of our mind. I wish I had some action figures to show what I'm talking about.

So letting things... you know, this is all eight aspects of consciousness, including the karmic momentum that we have stored up. This is a liberating out, particularly in the sleep state. And when we have drama in our life, like when we have a fight or something, there's strong liberating out in those situations. And you'll find that every time, if you have a habit of something---a desire, jealousy, pride, whatever---every time that same habit, your old friend, cycles through, it will become less and less impactful, right? Less and less binding there. As long as things are in the flow of self-liberation, that is.

So any comments or questions about that? Got it, right? Effortless abiding. Let it all continue---our perspectives, our moods---all just release, release, release, and try that flavor out. And that's what I was trying to express to our friend in the last session was that: try it out. Try it. Cause we feel obligated to think about stuff, don't we?

And not everybody has the choice to see, "I am strongly thinking about something. My frontal lobe is weighing down. I'm elaborating. I'm creating scenarios." Not everybody sees the opportunity that "I can actually let this go right now."

"No, but I got... I got to." Sorry. No, that's how we do. And then it grabs our body. It grabs our mood. It affects everybody around us. "I got to think about this!" Wake up! No, no you don't. You don't have to!

"Yes I do! Leave me alone! I'll give you 10 reasons why I'm an MF-er, why I need to be thinking about this right now."

We should all do that just for the heck of it. Pick some topic that we're always thinking about and just create 10 reasons why we need to be persistently occupied by this topic, you know, persistently thinking about it. These are cultural spells getting in our head. People's pain getting in our head, right? Stories constructed from the library of the delusional. Every word, with all due respect, is an empty appearance.

#archive_minimal("October 10, 2025", "Turning awareness on...", "https://www.youtube.com/watch?v=GlDv6nxHQbY")
