#import "/template.typ": *

= The Spheres of Conception

I did want to continue on with this fourth foundation of mindfulness and basically how we begin to verify and access. And for context, for people who are interested, this is a Dzogchen context so it's a little bit different than what you might see in mindfulness meditation, placement or object-based meditations, body scanning, Brahma Vihara type stuff, Tonglen even. Here there's nothing to do; there's no effort.

But somehow we want to make sure that we're not being stuck into these fields of consciousness. For example, in a mood. When you're only in the mood and you don't really feel like you have anywhere else to go, or there's some kind of thought proliferation that's taking you over, subjugating your experience. And in that way, we can point each other a little bit outside of that mood and say, "Hey, yes, you are here, but you can reorientate to a little bit of a broader scope."

And so within Dzogchen, ultimately, what we're sharing is the way of abiding. So a little bit outside of Trekchö and Tögal as they're introduced. It's more from once you've been introduced to clear light awareness, and many of you have also been introduced to bindus. Well, now you can practice Dzogchen Samatha-Vipassanā. So stability into awareness is the main practice. And you have constant revelation with that. You'll see, "Oh wow, this mood has been possessing me. I have been really caught up on those thoughts for decades." Lots of revelation; it's quite beautiful.

And just like when we discovered the microscope, I said this last time, we discovered a whole new world that we had never seen before. And we did this with the telescope too. All of a sudden we could see things we could never notice before, although they were there. And so now you have the scope of awareness. This is not like a telescope or a microscope---the lens is like space and it's volumetric and it's very, very thin, and you can see the clear light shimmer in this scope. And when you access this, it's the new scientific tool to discover the new world; and many of you obviously have already been discovering.

And so thankfully, with the eight aspects of consciousness and many other factors, like the 52 mental formations and the fetters and all this, we have the psychology, the Dharma psychology. But to me it's useful to recognize the spheres of conception. To at least just---oh, yeah, there it is---that's all you have to do. Nothing to modify or analyze beyond recognizing when we're in the spheres of conception. And so of course that's the subject, action, and object, triad---trichotomy.

So many meditators can sit here in the sphere of subjectivity. There's not really much action sphere happening. They've managed to subdue that, pacify that, or whatever, and so we can just sit here in our subjectivity, even though the whole world is around us. And this is a kind of absorption practice, not really Dzogchen. It's helpful, but it's still quite limited. And so I could sit here right now and if I have a thought like "mantras are great." If I have that one thought and that one thought only, "mantras are great," well, I can contain it; it's within the aquarium of my awareness.

But am I containing the sounds the same way? The bus, the person walking across the street? Typically not. We look at them and activate the subject, action, object trichotomy. "Oh, look what they're wearing." You start to---"Who's in that car over there?" And you're really giving this subjectivity life now. And as awareness practitioners, you can see that when you go out and about. And then you can try the other flavor: what's it like when I just leave this in awareness, including the subjectivity? Then there's a softening of division.

Making sense so far? Very good. Any questions, just ding on in there, okay? Because this is a little bit more advanced. If you're only in the thoughts, then you're stuck in a sort of concentric trichotomy: the thinker thinking thoughts about something. It's all located here, the three spheres overlapping. As congested as you could get, like that---as small as we could get.

So when the thought is released, there could be a feeling of me still sitting here---a subjectivity---a sense of a reference point. And in meditation, if we release all focus on objects or thoughts or feelings, then you may come to find that this is just here, this reference point. You cannot really notice this, recognize this, if you're stuck in thoughts, in that constant current of proliferation. So to be fair, you cannot demand freedom then. If you're drinking the caffeine every day and knowing that it's speeding up your mind, knowing that it's pulling on your emotions and knowing that it's messing up your body, you can't demand freedom---you can expect no freedom till you get over it.

I don't know how people do the two, three cups stuff because I notice just slightly the nervous system in my stomach even when I'm not on coffee. I could just get a little nervous or something and boom, it's clenching my organs. You know, I just personally, I can't do it, but either way, I'm not going to go on an anti-caffeine rant here; I think I've done that enough. And by the way, there are no rules. There are only guidelines and advice, but it is a little bit tragic to never get out of that thought current because it just keeps going and going. There's no space in between the thoughts.

Would you feel sad if you saw a little mousey that was doped up on some kind of drug and it just ran in circles and circles and circles? It couldn't stop running into circles? You would feel sad for this mouse. So really coming out of the thought proliferation, ruminations, whatever, is the key to notice the cognition---the cognitive basis. I recently quoted, I think it was David Bohm, quantum physicist, who said that if thought is the foundation of reality, then we ought to start doing something about thought. I was like, "Wow, quantum physicist, he even hasn't seen awareness," which would be the real basis of reality. But he's so much in his thoughts that he thinks thinking, that thoughts are the basis---which they are the basis for a lot of creation. That's why people are so interested in your thoughts and which thoughts you're having. They need you to be on their collective page in order for their illusory realities to come true. God forbid you think for yourself.

So we have these three spheres here and that's what's self-liberating. That is what we place in the state of cessation. _Rangdrol_ in Tibetan: self-liberation. So if I abide here now, talking to a whole bunch of people, maybe I have some insecurities come up about speaking or my tone of voice or the words that I'm choosing. As I'm speaking to you, this is visible. I can let it come and go instead of making a deal about it.

And make no mistake, a real awareness practitioner embraces their anger, their jealousy, their pride, their confusion, their insecurities. We say thank you. I'm the first to see it. First and foremost, because you have a lot of people out there that love to chastise you and say, "Look how angry you are. Look how bad of a practitioner you are." And you could say, "I know. I see it even more than you see it."

Nobody should be psychoanalyzing you unless you have scheduled an appointment with them. That is for you to do as awareness practitioners. Awareness is constantly psychoanalyzing without effort. So we enter the stream of cessation. You understand? Why I don't get on board with Nirodha Samapatti being a zombie state? Because we actually go into that kind of stuff---we witness great cessation, great self-liberation happening within the view.

So not only can somebody like me who just wanted to get away from their trauma, just wanted to heal some wounds---but I also get this magical freedom that's coming along that I didn't expect actually. I was incredibly skeptical, perhaps even cynical. Yeah, thankfully the Dharma is holding up to its name. It's the truth.

So that's where we get into this reference point, the subjectivity. It's not for everybody. That is your safety mechanism. That is your eggshell. That is your comfort zone. When that starts to go away and your stories and your identities go away, you're going to lose everything that you thought you were---which is a bunch of negativity usually. We don't think so good about ourselves. I just didn't want to hurt anymore, but I ended up finding lineage, luminosity, friends. Enlightenment.


#archive_minimal("February 09, 2026", "Dharma talk: Spheres...", "https://www.youtube.com/watch?v=aYFr-_meg4Q")
